name: vcard_app
description: A digital business card made with Flutter.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpg
    - assets/qrcode.png
